<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/controllers/controller.php';

$api = new Controller();

if ($_SERVER['REQUEST_METHOD'] == 'GET'){

    if ( (isset($_GET['organization'])) && (isset($_GET['number'])) ){
        //Obtener de organizacion la posicion concreta
        echo $api->getByOrganization($_GET['organization'], $_GET['number']);

    } else if(isset($_GET['organization'])){
        //Obtener de organizacion numero y repositorio mayor
        echo $api->getByOrganization($_GET['organization']);
        
    } else if(isset($_GET['number'])){
        //Obtener la posicion concreta
        echo $api->getByNumber($_GET['number']);
    }

}

